version: '2'

# same as 
# docker run -p 80:4000 -v $(pwd):/site bretfisher/jekyll-serve

services:
  drupal:
    image: drupal
    ports:
      - '8080:80'
    volumes: 
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: hiep21995446
     


