# create your drupal and postgres config here, based off the last assignment
version: '2'

# same as 
# docker run -p 80:4000 -v $(pwd):/site bretfisher/jekyll-serve

services:
  drupal:
    image: custom-drupal
    build: .
    ports:
      - '8080:80'
    volumes: 
      - drupal-modules:/var/www/html/modules 
      - drupal-profiles:/var/www/html/profiles 
      - drupal-sites:/var/www/html/sites 
      - drupal-themes:/var/www/html/themes 
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: hiep21995446
    volumes: 
      - drupal-data:/var/lib/postgresql/data

volumes: 
    drupal-data:
    drupal-modules:
    drupal-profiles:
    drupal-sites:
    drupal-themes:  
     


